name: Ships
version: 6.0.0.0
main: org.bships.plugin.ShipsMain
api-version: 1.13
description: Move a structure within a single click
website: https://dev.bukkit.org/projects/ships
author: mosemister
commands:
  ships:
    description: All ships commands
    aliases: [vessels]
    usage: ships <args>
  shipstest:
    description: Test the compatibility layer for ships
    usage: shipstest [args]
permissions:
    ships.remove.other:
        description: Allows the user to remove other peoples ships
        default: OP
    ships.cmd.info:
        description: Allows the user to use the '/ships info' command
        default: true
    ships.cmd.blockinfo:
        description: Allows the user to use the '/ships blockinfo' command
        default: false
    ships.cmd.shiptype.create:
        description: Allows the creation of new custom ship types
        default: OP
    ships.cmd.config.set:
        description: Allows the setting of config values by command
        default: OP
    ships.cmd.config.view:
        description: Allows the viewing of config values by command
        default: false
    ships.cmd.autopilot:
        description: Allows the use of the autopilot command
        default: false
    ships.cmd.blocklist.view:
        description: Allows the viewing of the blocklist
        default: false
    ships.cmd.blocklist.set:
        description: Allows the setting of the blocklist
        default: OP
    ships.cmd.ship.track:
        description: Allows the viewing of what ships sees
        default: true
    ships.cmd.ship.eot:
        description: Allows the use of the EOT command
        default: false
    ships.cmd.ship.crew:
        description: Allows the use of the crew command
        default: true
