name: Ships
version: 6.0.0.0
main: org.bships.plugin.ShipsMain
api-version: 1.13
commands:
  ships:
    description: All ships commands
    usage: ships <args>
  shipstest:
    description: Test the compatibility layer for ships
    usage: shipstest [args]